// Ajivak-svelte/src/components/HistorySection.svelte
<script>
    let showDetails = false;
  
    function toggleDetails() {
      showDetails = !showDetails;
    }
  </script>
  
  <section id="history">
    <h1 class="center-text">Historic Figures</h1>
    <!-- svelte-ignore a11y_click_events_have_key_events -->
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div class="card center-text" on:click={toggleDetails}>
      <h3>महान आजीवक मक्खलि गोसाल</h3>
      <h4>Mahan Ajivak Makkhali Gosal</h4>
    </div>
    {#if showDetails}
      <div class="details det">
        <p>महान आजीवक मक्खलि गोसाल, महावीर और बुद्ध से बड़ी उम्र के थे।...</p>
      </div>
    {/if}
  </section>
  
  <style>
    .center-text {
      text-align: center;
    }
  
    .card {
      background: #f4f4f4;
      border: 1px solid #ddd;
      border-radius: 5px;
      padding: 1rem;
      margin: 0.5rem 0;
      cursor: pointer;
    }
  
    .details {
      background: #d3eec9;
      border-left: 3px solid #333;
      padding: 1rem;
      margin: 0.5rem 0;
    }
  </style>

// Ajivak-react/ajivak-website/src/components/HistorySection.jsx
import React, { useState } from 'react';

const HistorySection = () => {
  const [showDetails, setShowDetails] = useState(null);

  const toggleDetails = (id) => {
    setShowDetails(showDetails === id ? null : id);
  };

  return (
    <section id="history" className="my-8">
      <h1 className="text-center text-2xl font-bold">Historic Figures</h1>
      <div className="card bg-gray-100 p-4 my-2 rounded-lg cursor-pointer" onClick={() => toggleDetails('history1')}>
        <h3 className="text-xl font-semibold">महान आजीवक मक्खलि गोसाल</h3>
        <h4 className="text-lg">Mahan Ajivak Makkhali Gosal</h4>
      </div>
      {showDetails === 'history1' && (
        <div className="details bg-[#d3eec9] p-4 my-2 border-l-4 border-[#333]">
          <p>महान आजीवक मक्खलि गोसाल, महावीर और बुद्ध से बड़ी उम्र के थे।...</p>
        </div>
      )}
    </section>
  );
};

export default HistorySection;
